steps:
  # Build and deploy the labs website.
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |      
        ./mklabs.sh
        gsutil cp -r mkdocs/labs-site gs://labs-$BRANCH_NAME-website/
