name: deploy_docs

on:
  push:
    branches: [ mkdocs ]

  workflow_dispatch:
env:
  BUCKET: gs://arxiv-docs-develop

jobs:
  preview_develop_docs:

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/mkdocs
          fetch-depth: 1

      # - name: 'Generate template for mkdocs from arxiv-base'
      #   working-directory: ./mkdocs
      #   run: ./prep_for_mkdocs.sh

      # - name: 'Build docs'
      #   working-directory: ./mkdocs
      #   run: mkdocs build

      # see https://github.com/marketplace/actions/authenticate-to-google-cloud#setup
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/586134671000/locations/global/workloadIdentityPools/github-arxiv-docs-pool/providers/github-oidc-provider'
          service_account: 'github-sa@arxiv-docs.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Upload HTML static site to GS'
        #        run: gsutil -m rsync -d -c -r mkdocs/site $BUCKET
        run: gcloud version
        run: gsutil ls $BUCKET


      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CI_CHANNEL }}
          SLACK_MESSAGE: "Deployed ${{github.repository}} ${{github.ref_name}} to https://TODO-add-URL/index.html"
