name: deploy_docs

on:
  push:
  pull_request:
    branches:
      - develop

jobs:
  preview:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Generate template
      working-directory: ./mkdocs
      run: ./scripts/deploy_to_s3.sh

    - name: Build docs
      working-directory: ./mkdocs      
      run: mkdocs build

    - uses: shallwefootball/s3-upload-action@master
      name: Upload S3
      id: S3
      with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_GITHUB_ACTION_CICD }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_GITHUB_ACTION_CICD }}
          aws_bucket: ${{ secrets.STATIC_CDN_AWS_S3_BUCKET }}
          source_dir: 'mkdocs/site'
          destination_dir: ${{ github.ref }}
          
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      
